## 1 numpy简介
numpy:开源的python科学计算模块，用于数据快速处理；

numpy支持矩阵与数组操作，计算速度快，是Python中科学计算的基础库；

numpy优点：
1. 底层使用C语言实现，计算速度快
2. numpy支持均值，累积和，方差等运算，可以直接使用；
3. numpy处理数据方式灵活，支持excel, csv等多种方式数据导入；


In [1]:
import numpy as np
values = np.array([1,2,3,4,5])
print(values)
print(type(values))


[1 2 3 4 5]
<class 'numpy.ndarray'>


## 2 numpy使用
### 2.1 ndarray

1. numpy中基本数据结构；
2. ndarray对象索引从0开始
3. 所有元素是同一种类型；
4. 与列表类似，支持切片等操作；


In [2]:
#一维ndarray
print(np.array([1,2,3]))
#二维ndarray,元素类型为float32
print(np.array([1,2,3], dtype='f' ,ndmin=2))

[1 2 3]
[[1. 2. 3.]]


#### 2.1.1 ndarry轴与秩
轴（axis）：每一个线性的数组称为是一个轴；

秩（rank）：维度

In [3]:
nd = np.array([1,2,3], ndmin=2)
print(f'ndim:{nd.ndim}')   # 秩
print(f'shape:{nd.shape}')  #维度
print(f'size:{nd.size}')   #元素数量
print(f'dtype:{nd.dtype}')  #元素类型

ndim:2
shape:(1, 3)
size:3
dtype:int32


In [4]:
#一维
a = np.zeros(10)
print('zeros:\n',a)
#二维
a = np.ones((2,10))
print('ones:\n',a)
#根据指定数据形状
b = np.empty_like(a)
print('empty_like:\n',b)
#arange:
a = np.arange(0,20, 2)
print('arange:\n',a)

zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
empty_like:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
arange:
 [ 0  2  4  6  8 10 12 14 16 18]


In [5]:
# np.radom相关方法
#根据指定形状产生随机值
print("random.rand:\n", np.random.rand(2,3))
#根据指定形状产生指定范围随机值
print('random.randint:\n', np.random.randint(10, 20, size=(2,10)))

random.rand:
 [[0.22869702 0.81646748 0.14623549]
 [0.78226625 0.56383522 0.76761393]]
random.randint:
 [[16 19 12 18 18 19 10 15 16 18]
 [15 18 15 14 14 10 19 10 19 13]]


In [6]:
# reshape方法：作用：调整array的新装，返回新的ndarray对象
a = np.arange(10)
b = a.reshape(2,5)
print('a.reshape(2,5):\n',b)
print('b.reshape(10):\n', b.reshape(10))

a.reshape(2,5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b.reshape(10):
 [0 1 2 3 4 5 6 7 8 9]


In [7]:
# ndarray对象转其他数据结构
a = np.arange(10)
print(a.tolist())
print(a.tobytes())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00'


### 2.2 numpy的数据类型


In [8]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [9]:
type(a[0])

numpy.int32

In [10]:
a = np.array(range(10),dtype=np.int8)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [11]:
a = np.array(range(10),dtype='b')
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [12]:
a = np.array(range(10),dtype='f')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [13]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.intc,
 5: numpy.intc,
 'uint': numpy.uint32,
 'I': numpy.uintc,
 6: numpy.uintc,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'ulong': numpy.uint32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex128,
 'F': numpy.complex

In [14]:
a.astype('U')

array(['0.0', '1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0',
       '9.0'], dtype='<U32')

### 2.3 numpy访问与修改
#### 2.3.1 一维array


In [15]:
import numpy as np
a = np.arange(25)
#索引0对应值：
v = a[0]
print(v)
#索引为10值：
v = a[10]
print(v)
#切片操作：
v = a[10:20]
print(v)
v = a[20:]
print(v)
v = a[10:20:2]
print(v)
v = a[20:10:-2]
print(v)

0
10
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24]
[10 12 14 16 18]
[20 18 16 14 12]


#### 2.3.2 numpy中的轴
轴是指数组沿着某个方向的线性序列，也就是数组的维度。一维数组有一个轴，二维数组有两个轴，以此类推。轴的数量也称为秩，它表示数组的维度数量。例如，一个二维数组的秩为2，一个三维数组的秩为3。

In [16]:
#二维array
import numpy as np
a = np.arange(25)
#2x2矩阵
a = a.reshape(5,5)
print(a)
#取a[0]
print('->a[0]:\t\t',a[0])
#取a[0][0]
print('->a[0][0]:\t',a[0][0])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
->a[0]:		 [0 1 2 3 4]
->a[0][0]:	 0


In [17]:
#取前三行
a[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
#取指定行
a[[1,2,4]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [19]:
#取第二列
a[:,1]

array([ 1,  6, 11, 16, 21])

In [20]:
#取1，3两列
a[:,[1,3]]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [21]:
#三维array
import numpy as np
a = np.arange(27)
#2x2矩阵
a = a.reshape(3,3,3)
print(a)
#取a[0]
print(a[0])
#取a[0][0]
print('->a[0][0]:\t',a[0][0])
print('->a[0][0][0]:\t',a[0][0][0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
->a[0][0]:	 [0 1 2]
->a[0][0][0]:	 0


In [22]:
#array修改
a = np.arange(10)
print(a)
#修改一个元素
a[0] = 10
print(a)
#修改多个元素
a[:5] = 10
print(a)

[0 1 2 3 4 5 6 7 8 9]
[10  1  2  3  4  5  6  7  8  9]
[10 10 10 10 10  5  6  7  8  9]


### 2.4 numpy计算
#### 2.4.1 基本计算

In [23]:
# numpy广播： boardcasting
a = np.arange(10)
print(a)
print(a*10)
print(a+1)
print(a/2)


[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
[ 1  2  3  4  5  6  7  8  9 10]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [24]:
# array之间计算
a = np.arange(5)
b = np.array([1,2,3,4,5])
print(a)
print(b)
print(a+b)
print(a*b)

[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5 7 9]
[ 0  2  6 12 20]


In [25]:
# 多维array之间计算
t = np.arange(10).reshape(2,5)
a = np.ones_like(t)
b = np.full_like(t, 10)
print(a)
print(b)
print(a+b)

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
[[11 11 11 11 11]
 [11 11 11 11 11]]


In [26]:
import numpy as np
a = np.arange(10)
print(a)
#求和，最大，最小，极差
print(np.sum(a), np.max(a), np.min(a), np.ptp(a))
#方差，中位数，
print(np.var(a), np.median(a))
#累加和:[a[0], a[0]+a[1], a[0]+a[1]+a[2], ...]
print(np.cumsum(a))

[0 1 2 3 4 5 6 7 8 9]
45 9 0 9
8.25 4.5
[ 0  1  3  6 10 15 21 28 36 45]


#### 2.4.2 多维array计算
多维array指定axis，可以得到不同效果，在计算常用指标，发挥奇效。
- shape不同不能计算
- 一维array与多维array的行相同，可以计算
- 一维array与多维array的列相同，可以计算

In [27]:
import numpy as np
a = np.arange(10)
a = a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
#指定axis为1,按行进行计算
print(np.sum(a, axis=1))
#指定axis为0：按列进行计算
print(np.sum(a, axis=0))

[10 35]
[ 5  7  9 11 13]


In [29]:
b = np.array(range(1,3)).reshape(2,1)
print(b)
c = np.array(range(0,5))
print(c)

[[1]
 [2]]
[0 1 2 3 4]


In [30]:
# 不同长度相加
print(a+b)
print(a+c)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]]


In [31]:
t = np.arange(8).reshape(2,2,2)
print(t)
for i in range(0,3):
    print()
    print("axis=%d:\n"%i,t.sum(axis=i))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

axis=0:
 [[ 4  6]
 [ 8 10]]

axis=1:
 [[ 2  4]
 [10 12]]

axis=2:
 [[ 1  5]
 [ 9 13]]


In [32]:
b = np.array([[[1,2,3,4],[1,3,4,5]],[[2,4,7,5],[8,4,3,5]],[[2,5,7,3],[1,5,3,7]]])
print(b)
print("shape =",b.shape)
for i in range(0,3):
    print()
    print("axis=%d:\n"%i,b.sum(axis=i))

[[[1 2 3 4]
  [1 3 4 5]]

 [[2 4 7 5]
  [8 4 3 5]]

 [[2 5 7 3]
  [1 5 3 7]]]
shape = (3, 2, 4)

axis=0:
 [[ 5 11 17 12]
 [10 12 10 17]]

axis=1:
 [[ 2  5  7  9]
 [10  8 10 10]
 [ 3 10 10 10]]

axis=2:
 [[10 13]
 [18 20]
 [17 16]]


### 2.5 numpy数据拼接分割
#### 2.5.1 多个array拼接

In [33]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
print(f'{a}\n---\n{b}')

[[1 2]
 [3 4]]
---
[[5 6]
 [7 8]]


In [34]:
#轴为1进行拼接
'''
[[1,2],[3,4]]
[[5,6],[7,8]]
结果
[1,2,]+[5,6]
[3,4]+[7,8]
'''
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [35]:
#轴为0进行拼接
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### 2.5.2 多个数组的堆叠
np.stack(arrays, axis=0, out=None) 基本理解：arrays，沿着axis进行堆叠，类似穿起来，而不是拼接 例如：

In [36]:
a = np.arange(0,2)
b = np.arange(2,4)
c = np.arange(4,6)
'''
[0, 1]
[2, 3]
[4, 5] ->
沿着axis=0拼接：
[[0, 1],
[2, 3],
[4, 5],]
'''
np.stack((a,b,c), axis=0)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
a = np.arange(0,2)
b = np.arange(2,4)
c = np.arange(4,6)
'''
[0, 1]
[2, 3]
[4, 5] ->
沿着axis=1拼接：
[[0,2,4],
[1,3,5]]
'''
np.stack((a,b,c), axis=1)

array([[0, 2, 4],
       [1, 3, 5]])

#### 2.5.3 np.hstack与np.vstack
分别为水平拼接与垂直拼接


In [38]:
a = np.arange(0,2)
b = np.arange(2,4)
c = np.arange(4,6)
print(np.hstack((a,b,c)))
print(np.vstack((a,b,c)))


[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


#### 2.5.4 numpy分割
split方法：将制定的array按照aixs分割成制定值

np.split(ary, indices_or_sections, axis=0)


In [39]:
np.split(np.arange(4),2, axis=0)

[array([0, 1]), array([2, 3])]

In [40]:
a = np.arange(8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [41]:
#按照axis=0进行切分，分成2份
np.split(a, 2, axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]

In [42]:
#按照axis=1进行切分，分成2份
np.split(a, 2, axis=1)

[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]

#### 2.5.5 vsplit与hsplit
vsplit沿着垂直轴切分

hsplit沿着水平轴切分

In [43]:
a = np.arange(10)
np.hsplit(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [44]:
a = np.arange(10).reshape(2,5)
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

### 2.6 numpy其他操作
#### 2.6.1 nan与缺省值处理
- Nan是nunpy和pandas中用于标识缺失数据
- 
None:Python 中对象，不能与Nan混淆一起

一个例子：某同学两次考试，有一次因为某些情况没有参加，数据格式如下：

In [45]:
v1 = np.array([[90, 100],[np.nan, 100]])
v1

array([[ 90., 100.],
       [ nan, 100.]])

#### 2.6.2 nan判断

In [46]:
np.isnan(v1)

array([[False, False],
       [ True, False]])

#### 2.6.3 boolean索引
array的值都为True或者False；

例如`：array([[False, False],[ True, False]]`) 获取所有nan值：


In [47]:
np.isnan(v1)

array([[False, False],
       [ True, False]])

In [48]:
v1[np.isnan(v1)]

array([nan])

In [49]:
#获取非nan值
v1[np.isnan(v1) == False]

array([ 90., 100., 100.])

#### 2.6.4 np.all与any
np.all(a, axis=None, out=None, ):沿着给定的axis判断是否有元素为0，为0返回False,不设置axis，判断所有元素

np.any(a, axis=None, out=None, )：沿着给定的axis判断是否有元素不为0，为0返回False，不设置axis，判断所有元


In [50]:
a = np.arange(10)
print(a)
print(np.all(a))

[0 1 2 3 4 5 6 7 8 9]
False


In [51]:
a = np.arange(10).reshape(2,5)
print(a)
#沿着axis=0，简单理解垂直轴
print(np.all(a, axis=0))
#沿着axis=1，简单理解水平轴
print(np.all(a, axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]


In [52]:
b = np.zeros_like(a)
print(b)
print(f'a:{np.all(a)},b:{np.all(b)}')
print(f'a:{np.any(a)},b:{np.any(b)}')

[[0 0 0 0 0]
 [0 0 0 0 0]]
a:False,b:False
a:True,b:False


In [53]:
a = np.array([1, None])
print(a)
print(np.any(a))
print(np.all(a))

[1 None]
1
None


In [54]:
a = np.random.randint(10,100,size=10)
print(a)
print(a[a>59])

[63 53 11 20 12 50 28 35 76 90]
[63 76 90]


#### 2.6.5 np.where
`where(condition, [x, y])`:
如果给定x,y,满足条件condition，输出x，不满足输出y；

如果没有x,y,返回满足条件对应的值的索引；

示例：随机生成成绩单，判断是否及格

In [55]:
a = np.random.randint(30,100, 10)
print(a)
np.where(a>=60, 'pass', 'failed')

[88 52 88 59 46 85 51 89 98 64]


array(['pass', 'failed', 'pass', 'failed', 'failed', 'pass', 'failed',
       'pass', 'pass', 'pass'], dtype='<U6')

In [56]:
np.where(a>=60)

(array([0, 2, 5, 7, 8, 9], dtype=int64),)

In [57]:
a[np.where(a>=60)]

array([88, 88, 85, 89, 98, 64])

In [58]:
'''
在Python请独立编写查找函数：def binary_search (nums, target) 
要求： 
1：使用二分查找实现 
2：如果在text中找到value，返回对应的索引，否则返回-1
'''
def binary_search(nums, target):
    left, right = 0, len(nums) - 1  # 初始化左右指针

    while left <= right:
        mid = left + (right - left) // 2  # 计算中间索引，防止溢出

        if nums[mid] == target:  # 如果中间值等于目标值
            return mid  # 返回中间索引
        elif nums[mid] < target:  # 如果中间值小于目标值
            left = mid + 1  # 更新左指针为中间索引加1
        else:
            right = mid - 1  # 如果中间值大于目标值，更新右指针为中间索引减1

    return -1  # 目标值不在数组中，返回-1

# 示例用法：
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
target = 7
result = binary_search(nums, target)
if result != -1:
    print(f"目标值 {target} 在数组中的索引是 {result}")
else:
    print(f"目标值 {target} 不在数组中")

目标值 7 在数组中的索引是 6
